import { ClerkProvider } from '@clerk/nextjs' //
import './globals.css' //globals.css파일을 전체 프로젝트에 적용
import { Inter } from 'next/font/google' // 구글 폰트 사용
import Header from '../components/Header'

const inter = Inter({ subsets: ['latin'] }) // 이 코드는 아직 먼지 모름

export const metadata = {
  // 메타데이터 관리하는 코드라고함
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  //   RootLayout 지정
  // 모든 페이지들에 적용되는 레이아웃 설정
  // Navbar, Footer 등을 지정 가능
  // Children은 여러 세부 페이지들을 나타냄

  return (
    // ClerkProvider는 뭔지 모르겠음
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* 아래 코드를 지우면 상단의 메뉴바가 없어진다. */}
          <Header />

          <main className="container">
            <div className="flex items-start justify-center min-h-screen">
              {/* 아래 코드의 children을 지우면 웹페이지의 home이 없어진다. */}
              <div className="mt-20">{children}</div>
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
